### ISSUE TITLE
AppIcon.appiconset missing the Xcode required Contents.json file

### ISSUE THREAD

**Issue by scarefree** [jerolimov/app_icon_template#3]
Sketch Version 52.6
Mac OS X 12
Xcode 13

**Comment by thinkmobilede** [comment]
Sketch does not export the contents.json, but it is in the relative path of the existing icons. To export an icon set you first have to export it to the existing folder (which contains a contents.json) and then you can drag/copy this folder into your Assets-Folder.

**Comment by christoph-jerolimov** [comment]
Exactly. Thanks @thinkmobilede

@scarefree You need to export your content into the current project folder. Let us know if this doesn't work for you. Until then I will close this ticket.

You can find the `Contents.json` file here https://github.com/jerolimov/app_icon_template/blob/master/ios/AppIcon.appiconset/Contents.json
